# Generated by Django 5.1.6 on 2025-02-13 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_status_tarefa_title_alter_tarefa_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='data_criacao1',
        ),
    ]
