# Generated by Django 5.1.6 on 2025-02-14 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_tarefa_data_criacao1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='status',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='Tarefa',
        ),
    ]
