# Generated by Django 5.2 on 2025-04-03 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='data_criacao',
        ),
    ]
