# Generated by Django 5.1.7 on 2025-04-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='categoria',
            field=models.CharField(choices=[('Música', 'Música'), ('Acampamento', 'Acampamento'), ('Workshop', 'Workshop'), ('Palestra', 'Palestra')], max_length=11),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
